DROP TABLE IF EXISTS comportements;
DROP TABLE IF EXISTS voitures;

CREATE TABLE comportements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE voitures (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);